# LAB 1

In [15]:
from vectors import *

In [16]:
test_vector = np.array([[1],[2],[3],[4],[5]])

In [17]:
get_vector(5)

array([[0.03638783],
       [0.94295997],
       [0.13267121],
       [0.55633729],
       [0.87128638]])

In [18]:
sparse = get_sparse_vector(20)
print(sparse.toarray())
print(sparse)

[[0.75752047]
 [0.67048734]
 [0.0288765 ]
 [0.88380681]
 [0.54116631]
 [0.        ]
 [0.        ]
 [0.15750398]
 [0.        ]
 [0.8359891 ]
 [0.43254573]
 [0.        ]
 [0.32324497]
 [0.        ]
 [0.        ]
 [0.2624826 ]
 [0.        ]
 [0.2796093 ]
 [0.65740275]
 [0.        ]]
<COOrdinate sparse matrix of dtype 'float64'
	with 12 stored elements and shape (20, 1)>
  Coords	Values
  (0, 0)	0.7575204720654801
  (1, 0)	0.6704873391000181
  (2, 0)	0.02887650027818367
  (3, 0)	0.8838068053434333
  (4, 0)	0.541166308917466
  (7, 0)	0.15750398353397788
  (9, 0)	0.8359890999472308
  (10, 0)	0.4325457259326795
  (12, 0)	0.3232449713332287
  (15, 0)	0.2624826044411087
  (17, 0)	0.279609300142169
  (18, 0)	0.6574027546993702


In [19]:
add(test_vector, test_vector)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [20]:
scalar_multiplication(test_vector, 5.0)

array([[ 5.],
       [10.],
       [15.],
       [20.],
       [25.]])

In [21]:
linear_combination(test_vector, [[5],[2],[3],[4],[5]])

array([59])

In [22]:
dot_product(test_vector, test_vector)

55.0

In [23]:
norm(test_vector, 1)

np.float64(15.0)

In [24]:
norm(test_vector, 2)

np.float64(7.416198487095664)

In [25]:
norm(test_vector, float("inf"))

np.float64(5.0)

In [26]:
distance(test_vector, [3,4,5,6,7])

np.float64(14.142135623730951)

In [27]:
cos_between_vectors(np.array([[1],[0]]), np.array([[0.5],[0.5]]))

45.00000000000001

In [28]:
cos_between_vectors([1,0], [0,1])

AttributeError: 'list' object has no attribute 'T'

In [ ]:
solves_linear_systems([[1,2], [3,5]], [1,2])

array([-1.,  1.])