# LAB 1

In [286]:
from vectors import *

In [287]:
test_vector = np.array([1,2,3,4,5])

In [288]:
get_vector(5)

array([[0.5232545 ],
       [0.47048337],
       [0.95487497],
       [0.84068107],
       [0.28045556]])

In [289]:
sparse = get_sparse_vector(20)
print(sparse.toarray())
print(sparse)

[[0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.59509416]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1 stored elements and shape (20, 1)>
  Coords	Values
  (8, 0)	0.5950941582635709


In [290]:
add(test_vector, test_vector)

array([ 2,  4,  6,  8, 10])

In [291]:
scalar_multiplication(test_vector, 5.0)

array([ 5., 10., 15., 20., 25.])

In [292]:
linear_combination(test_vector, [1,2,3,4,5])

array([55])

In [293]:
dot_product(test_vector, test_vector)

55.0

In [294]:
norm(test_vector, 1)

np.float64(15.0)

In [295]:
norm(test_vector, 2)

np.float64(7.416198487095663)

In [296]:
norm(test_vector, float("inf"))

np.float64(5.0)

In [297]:
distance(test_vector, [3,4,5,6,7])

np.float64(4.47213595499958)

In [298]:
cos_between_vectors([1,0], [0.5,0.5])

45.00000000000001

In [299]:
cos_between_vectors([1,0], [0,1])

90.0

In [300]:
solves_linear_systems([[1,2], [3,5]], [1,2])

array([-1.,  1.])