# LAB 1

In [2]:
from vectors import *

In [3]:
test_vector = np.array([1,2,3,4,5])

In [4]:
get_vector(5)

array([0.13785732, 0.45432384, 0.65723022, 0.44585068, 0.2020521 ])

In [5]:
sparse = get_sparse_vector(20)
print(sparse.toarray())
print(sparse)

[[0.30651892 0.         0.25202765 0.16263421 0.         0.
  0.         0.         0.         0.         0.52452728 0.84586242
  0.40429334 0.77048504 0.         0.         0.         0.
  0.71273168 0.3457331 ]]
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9 stored elements and shape (1, 20)>
  Coords	Values
  (0, 0)	0.306518915538773
  (0, 2)	0.25202765367383106
  (0, 3)	0.1626342085037814
  (0, 10)	0.524527275891549
  (0, 11)	0.8458624244575845
  (0, 12)	0.40429333738601625
  (0, 13)	0.7704850408811533
  (0, 18)	0.7127316847339267
  (0, 19)	0.345733104762197


In [6]:
add(test_vector, test_vector)

array([ 2,  4,  6,  8, 10])

In [7]:
scalar_multiplication(test_vector, 5.0)

array([ 5., 10., 15., 20., 25.])

In [8]:
linear_combination()

TypeError: linear_combination() missing 2 required positional arguments: 'vectors' and 'coeffs'

In [9]:
dot_product(test_vector, test_vector)

array([ 1,  4,  9, 16, 25])

In [ ]:
norm(test_vector, 1)

np.float64(15.0)

In [ ]:
norm(test_vector, 2)

np.float64(7.416198487095663)

In [ ]:
norm(test_vector, float("inf"))

np.float64(5.0)

In [13]:
distance(test_vector, [3,4,5,6,7])

np.float64(4.47213595499958)

In [ ]:
cos_between_vectors([1,0],[0.5,0.5])