# LAB 1

In [1]:
from vectors import *

In [2]:
test_vector = np.array([1,2,3,4,5])

In [3]:
get_vector(5)

array([0.81394258, 0.98265027, 0.86966736, 0.74855274, 0.91212234])

In [4]:
sparse = get_sparse_vector(20)
print(sparse.toarray())
print(sparse)

[[0.76331169 0.73235655 0.81725352 0.65536224 0.45136142 0.29614566
  0.73368038 0.         0.         0.         0.8882156  0.55819238
  0.73457841 0.04417755 0.99892292 0.14111471 0.35897607 0.
  0.65048325 0.        ]]
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15 stored elements and shape (1, 20)>
  Coords	Values
  (0, 0)	0.7633116851175711
  (0, 1)	0.7323565533470321
  (0, 2)	0.8172535212736955
  (0, 3)	0.6553622442940737
  (0, 4)	0.4513614219064742
  (0, 5)	0.29614566170178014
  (0, 6)	0.7336803799601397
  (0, 10)	0.8882155968131804
  (0, 11)	0.5581923849920836
  (0, 12)	0.7345784071154389
  (0, 13)	0.04417755380981847
  (0, 14)	0.9989229224978512
  (0, 15)	0.14111470518384417
  (0, 16)	0.3589760730157878
  (0, 18)	0.6504832477265915


In [5]:
add(test_vector, test_vector)

array([ 2,  4,  6,  8, 10])

In [6]:
scalar_multiplication(test_vector, 5.0)

array([ 5., 10., 15., 20., 25.])

In [ ]:
linear_combination(test_vector, [1,2,3,4,5])

np.int64(15)

In [ ]:
dot_product(test_vector, test_vector)

array([ 1,  4,  9, 16, 25])

In [ ]:
norm(test_vector, 1)

np.float64(15.0)

In [ ]:
norm(test_vector, 2)

np.float64(7.416198487095663)

In [ ]:
norm(test_vector, float("inf"))

np.float64(5.0)

In [ ]:
distance(test_vector, [3,4,5,6,7])

np.float64(4.47213595499958)

In [ ]:
cos_between_vectors([1,0], [0.5,0.5])

np.float64(45.00000000000001)

In [ ]:
cos_between_vectors([1,0], [0,1])

np.float64(90.0)

In [ ]:
solves_linear_systems([[1,2], [3,5]], [1,2])

array([-1.,  1.])